# Generated by Django 3.0.6 on 2020-05-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0002_event_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="default_timezone",
            field=models.TextField(default="America/New_York"),
        ),
    ]
