# Generated by Django 3.0.6 on 2020-05-04 22:14

from django.db import migrations, models

import scheduling.models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0005_auto_20200504_2158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="uuid",
            field=models.UUIDField(
                default=scheduling.models._default_uuid,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
