# Generated by Django 3.0.6 on 2020-05-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_auto_20200504_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='reschedule_after',
            field=models.IntegerField(default=30),
        ),
    ]
