# Generated by Django 3.0.6 on 2020-05-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0013_auto_20200507_2228"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event", options={"ordering": ["-scheduled"]},
        ),
        migrations.AddField(
            model_name="event",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["schedule", "-scheduled"], name="scheduling__schedul_956adf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["schedule", "-inception"], name="scheduling__schedul_02d782_idx"
            ),
        ),
    ]
