apiVersion: v1
kind: Secret
metadata:
    name: tim-settings
type: Opaque
stringData:
    # Django settings
    DEBUG: "False"
    ALLOWED_HOSTS: "*"
    DJANGO_SECRET_KEY: ""
    TIME_ZONE: "America/New_York"

    # Redis configuration (if you use the default Kubernetes config, this will work)
    REDIS_CACHE_LOCATION: "redis://tim-redis.default.svc.cluster.local/0"
    CELERY_BROKER_URL: "redis://tim-redis.default.svc.cluster.local/1"
    CELERY_TASK_ALWAYS_EAGER: "False"

    # PostgreSQL settings
    DB_NAME: ""
    DB_USER: ""
    DB_PASSWORD: ""
    DB_HOST: ""