# Generated by Django 3.0.5 on 2020-05-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.TextField(
                        choices=[("todoist", "Todoist"), ("gcal", "Google Calendar")]
                    ),
                ),
                ("configuration", models.TextField()),
                ("authentication", models.TextField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling.Schedule",
                    ),
                ),
            ],
        ),
    ]
