# Generated by Django 3.0.6 on 2020-05-05 01:24

from django.db import migrations, models
import integrations.models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='authentication',
            field=models.TextField(default='{}', help_text='Must be valid JSON!', validators=[integrations.models._validate_json]),
        ),
        migrations.AlterField(
            model_name='integration',
            name='configuration',
            field=models.TextField(default='{}', help_text='Must be valid JSON!', validators=[integrations.models._validate_json]),
        ),
        migrations.AlterField(
            model_name='integration',
            name='service',
            field=models.TextField(choices=[('todoist', 'Todoist'), ('gcal', 'Google Calendar'), ('ics', 'External Calendar')]),
        ),
    ]
